AuctionHouse/Controllers/MenuController.cs
using AuctionHouse.Helpers;
using AuctionHouse.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AuctionHouse.Controllers
{
    public class MenuController : Controller
    {
        // GET: Menu
        public ActionResult MenuRenderHeader()
        {
            CookieCurrencyHelper.CheckCoockie();

            var currToReturn = CookieCurrencyHelper.GetCurrentCurrecny();

            return PartialView("_MenuRenderHeaderPartial", currToReturn);
        }
        public ActionResult MenuRenderSideBar()
        {
            List<CategoryViewModel> categoriesToView = new GetCategories().GetCategoriesForMenu();
            return PartialView("_MenuRenderSideBarPartial", categoriesToView);
        }

        public JsonResult SetCoockieValue(string value)
        {
            CookieCurrencyHelper.SetCoockieValue(value);
            return Json(true);
        }
    }
}

AuctionHouse/Views/Menu/_MenuRenderHeaderPartial.cshtml
@model AuctionHouse.Models.CurrencyViewModel
<!DOCTYPE html>
<html lang="en">

<body>
    <header id="header">
        <!--header-->
        <div class="header_top">
            <!--header_top-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="contactinfo">
                            <ul class="nav nav-pills">
                                <li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
                                <li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="social-icons pull-right">
                            <ul class="nav navbar-nav">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header_top-->

        <div class="header-middle">
            <!--header-middle-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="logo pull-left">
                            <a href="@Url.Action("Index","Home")"><img src="~/images/auction-icon-14.png" alt="" /></a>
                        </div>


                        <div class="btn-group pull-right">
                            <select class="form-control" id="currency" onchange="ChangeCurrency()">
                                <option value="@Model.ActiveCurrency">@Model.ActiveCurrency</option>
                                {@foreach (var currency in Model.Currencies)
                                {
                                    <option value="@currency">@currency</option>
                                }}
                            </select>
                        </div>

                    </div>
                    <div class="col-sm-8">
                        <div class="shop-menu pull-right">
                            <ul class="nav navbar-nav">
                                @{ if (User.Identity.IsAuthenticated)
                                    {
                                        if (HttpContext.Current.User.IsInRole("Admin"))
                                        {
                                            <li class="dropdown">
                                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                                    Admin Panel
                                                    <span class="caret"></span>
                                                </a>
                                                <ul class="dropdown-menu">
                                                    <li><a href="@Url.Action("Create", "Category")">Create Category</a></li>
                                                    <li><a href="@Url.Action("Create", "PaymentMethod")">Create PaymentMethod</a></li>
                                                </ul>
                                            </li>
                                        }
                                        <li class="dropdown">
                                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                                Member Area
                                                <span class="caret"></span>
                                            </a>
                                            <ul class="dropdown-menu">
                                                <li><a href="@Url.Action("Create", "Market")">Create Market</a></li>
                                                <li><a href="@Url.Action("Create", "Storage")">Create Storage</a></li>
                                                <li><a href="@Url.Action("ViewUser", "Market")">View my markets state</a></li>
                                                @*<li><a href="@Url.Action("ViewOrdersMarketOwner", "Order")">View my orders</a></li>*@
                                            </ul>
                                        </li>
                                        <li class=""><a href="@Url.Action("LogOut", "Account")">Log Out</a></li>
                                    }
                                    else
                                    {
                                        <li><a href="@Url.Action("Login", "Account")">Login</a></li>
                                        <li><a href="@Url.Action("Registration", "Account")">Registration</a></li>
                                    }}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header-middle-->

        <div class="header-bottom">
            <!--header-bottom-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-9">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="mainmenu pull-left">
                            <ul class="nav navbar-nav collapse navbar-collapse">
                                <li><a href="@Url.Action("Index","Home")" class="active">Home</a></li>

                                <li><a href="@Url.Action("ViewAll", "Market")">View all Markets</a></li>
                            </ul>
                        </div>
                    </div>                  
                </div>
            </div>
        </div><!--/header-bottom-->
    </header><!--/header-->

</body>
</html>

<script type="text/javascript">
    function ChangeCurrency() {
        var valueToChange = $("#currency option:selected").text();
        $.ajax({
            type: "POST",
            async: true,
            url: '@Url.Action("SetCoockieValue", "Menu")',
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({
                value: valueToChange,
            }),
            success: function (data) {
                //window.location.href = '/Home/Index/'
                location.reload();
            }
        });
    }
</script>

AuctionHouse/Views/Menu/_MenuRenderSideBarPartial.cshtml
@model IEnumerable<AuctionHouse.Models.CategoryViewModel>

<div class="col-sm-3">
    <div class="left-sidebar">
        <h2>Category</h2>
        <div class="panel-group category-products" id="accordian">
            <!--category-productsr-->
            @{ foreach (var category in Model)
                {
                    if (category.ChildCategory.Count == 0)
                    { <div class="panel panel-default">
                         <div class="panel-heading">
                              <h4 class="panel-title"><a href="@Url.Action("GetProducts","Category", new {Id = category.Id})">@category.CategoryType</a></h4>
                         </div>
                     </div>
                    }
                    else
                    {
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a  href="@Url.Action("GetProducts","Category", new {Id = category.Id})">
                                        <span class="badge pull-right"><i class="fa fa-plus" data-toggle="collapse" data-parent="#accordian" href="#@category.CategoryType"></i></span>
                                        @category.CategoryType
                                    </a>
                                </h4>
                            </div>
                            <div id="@category.CategoryType" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <ul>
                                        @foreach (var subCat in category.ChildCategory)
                                        {
                                            <li><a href="@Url.Action("GetProducts","Category", new {Id = subCat.Id})">@subCat.CategoryType</a></li>
                                        }

                                    </ul>
                                </div>
                            </div>
                        </div>
                    }


                }}
          
        </div><!--/category-products-->

    </div>
</div>