AuctionHouse/Models/CategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AuctionHouse.Models
{
    public class CategoryViewModel
    {
        public int Id { get; set; }
        public string CategoryType { get; set; }
        public int ParentId { get; set; }

        public List<CategoryViewModel> ChildCategory { get; set; } = new List<CategoryViewModel>();
    }
}

AuctionHouse/Controllers/CategoryController.cs
using AuctionHouse.Helpers;
using AuctionHouse.Models;
using AuctionHouse.RestSDK;
using AuctionHouse.RestSDK.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AuctionHouse.Controllers
{
    public class CategoryController : Controller
    {
        Configuration Api_Configuration;
        Client client;
        public CategoryController()
        {
            Api_Configuration = new Configuration(AppSettings.UrlServerForSDK());

            client = new Client(Api_Configuration);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CategoryViewModel category)
        {
            if (ModelState.IsValid)
            {
                CategoryDTO categoryToCreate = new CategoryDTO
                {
                    CategoryType = category.CategoryType
                };
                var serializedCategory = SerializeHelper.Serialize(categoryToCreate);
                var request = client.Categories.Create(serializedCategory);
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult GetProducts(int id, int page = 1)
        {
            int pageSize = AppSettings.PaginationPageSize();
            try
            {
                var response = client.Categories.GetProducts(id).Data;
                List<ProductViewModel> productsToReturn = response.Select(x => new ProductViewModel
                {
                    AuctionEndDate = x.AuctionEndDate,
                    BuyOut = Math.Round(x.BuyOut * CookieCurrencyHelper.NumberToMultiply()),
                    CurrentBet = Math.Round((x.CurrentBet > x.MinBet ? x.CurrentBet : x.MinBet) * CookieCurrencyHelper.NumberToMultiply()),
                    Id = x.Id,
                    ImageUrl = x.ImageUrl,
                    Name = x.Name,
                    Category = x.Category,
                    Storage = x.Storage,
                    Market = x.Market,
                    PaymentMethod = x.PaymentMethod,
                    Number = x.Number,
                    Description = x.Description
                }).ToList();
                IEnumerable<ProductViewModel> productsPerPages = productsToReturn.Skip((page - 1) * pageSize).Take(pageSize);
                PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = productsToReturn.Count };
                PaginationProductViewModel pagiantionModel = new PaginationProductViewModel { PageInfo = pageInfo, Products = productsPerPages };
                return View(pagiantionModel);
            }
            catch (Exception)
            {

                //throw;
            }
            return null;
        }
    }
}

AuctionHouse/Views/Category/Create.cshtml
@model AuctionHouse.Models.CategoryViewModel
<div class="row">
    @using (Html.BeginForm("Create", "Category", FormMethod.Post))
    {
        <p>Enter category:</p>
        <input type="text" class="form-control" name="CategoryType" placeholder="Category Type">
        <button type="submit" class="btn-default">Create</button>
    }
</div>

AuctionHouse/Views/Category/GetProducts.cshtml
@using AuctionHouse.Helpers
@model AuctionHouse.Models.PaginationProductViewModel

<div class="features_items">
    <!--features_items-->
    <h2 class="title text-center">@Model.Products.Select(x=>x.Category.CategoryType).FirstOrDefault()</h2>
    @{ foreach (var product in Model.Products)
        {
            <div class="col-sm-4">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            @{ if (product.ImageUrl != "")
                                {
                                    <a href="@Url.Action("GetProduct", "Product", new { id = product.Id })"> <img src="~/images/products/@product.ImageUrl " alt="" /></a>
                                }
                                else
                                {
                                    <a href="@Url.Action("GetProduct", "Product", new { id = product.Id })"> <img src="~/images/products/noimages.png" alt="" /></a>
                                }}
                            <h2>@product.Categories</h2>
                            <p>@product.Name</p>
                            <a href="" onclick="clickedProduct(@product.Id)" class="btn btn-default add-to-cart" data-toggle="modal" data-target="#myModal"><i class="fa fa-shopping-cart"></i>Place a bet</a>
                        </div>

                    </div>
                    <div class="choose">
                        <ul class="nav nav-pills nav-justified">
                            <li>Current bet: @product.CurrentBet</li>
                            <li>Buy out: @product.BuyOut</li>
                        </ul>
                    </div>
                </div>

            </div>
        }}


</div>
<div style="width:20%;margin: 0 auto; margin-bottom:5%;">
    @Html.PageLinks(Model.PageInfo, x => Url.Action("GetProducts", "Category", new { page = x }))
</div>

<script type="text/javascript">

    var productId;

    function clickedProduct(id) {
        window.productId = id;
    }

    function MakeBet() {
        var betValue = $("[name=CurrentBetToReturn]").val();
        $.ajax({
            type: "POST",
            async: true,
            url: '@Url.Action("Create", "BetHistory")',
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({
                id: window.productId,
                bet: betValue
            }),
            success: function (data) {
                location.reload();
            }
        });
    }


</script>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Place your bet</h4>
            </div>
            @{ if (!HttpContext.Current.User.Identity.IsAuthenticated)
                {
                 <h4 class="form-control">Please login or create account</h4>
                }
                else
                {
                    <div class="modal-body">
                        <input type="number" class="form-control" value="" name="CurrentBetToReturn">
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-default" onclick="MakeBet()" data-dismiss="modal">Make a bet</button>
                    </div>
                }}
           
        </div>

    </div>
</div>